version: '3'
services:
  db:
    image: postgres:latest
    env_file:
      - ./server/.env-prod-db
  web:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./server/.env-prod-web
    volumes:
      - ./server:/server
    ports:
      - "3000:3000"
    depends_on:
      - db
  vue:
    build: ./client
    ports:
      - "8000:8000"
