version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env-prod-db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env-prod-web
    volumes:
      - .:/server
    ports:
      - "3000:3000"
    depends_on:
      - db
